[2019-10-08 11:11:01,703::INFO::PyFunceble/__init__.py:1535@_command_line](PID12731): ARGS:
Namespace(adblock=False, aggressive=False, all=True, auto_continue=False, autosave_minutes=None, clean=False, clean_all=False, cmd=None, cmd_before_end=None, commit_autosave_message=None, commit_results_message=None, complements=False, database=False, database_type='mariadb', days_between_db_retest=None, debug=True, directory_structure=False, dns=['158.69.2.23'], domain=None, execution=True, file='/home/mitchellkrog/PyFuncebleTests/Phishing.Domains/input/ALL-feeds.lst', filter=None, hierarchical=False, host=False, http=False, iana=False, idna=True, ip=None, json=False, less=False, link=None, local=False, mining=False, multiprocess=False, no_files=False, no_logs=False, no_special=False, no_unified=False, no_whois=False, percentage=False, plain=True, processes=None, production=False, public_suffix=False, quiet=False, share_logs=False, simple=False, split=False, syntax=False, timeout=1, travis=False, travis_branch='master', url=None, url_file=None, user_agent=None, verify_ssl_certificate=False, whois_database=False)
[2019-10-08 11:11:02,196::INFO::PyFunceble/mysql.py:317@create_tables_and_apply_patches](PID12731): Created the missing tables. Applied all patched
[2019-10-08 11:11:02,197::INFO::PyFunceble/auto_save.py:97@__init__](PID12731): Authorized: False
[2019-10-08 11:11:02,198::INFO::PyFunceble/inactive_db.py:521@get_to_retest](PID12731): Getting the list of subjects to retest (DATASET WONT BE LOGGED)
[2019-10-08 11:11:03,112::INFO::PyFunceble/auto_continue.py:108@__init__](PID12731): Process authorized.
[2019-10-08 11:11:03,112::INFO::PyFunceble/auto_continue.py:130@__init__](PID12731): Process authorized, is the parent process and the file to test not indexed. Cleaning directory structure.
[2019-10-08 11:11:03,114::INFO::PyFunceble/clean.py:207@almost_everything](PID12731): Deleted: /home/mitchellkrog/PyFuncebleTests/Phishing.Domains/output/Analytic/POTENTIALLY_INACTIVE/down_or_potentially_down
[2019-10-08 11:11:03,125::INFO::PyFunceble/mysql.py:317@create_tables_and_apply_patches](PID12731): Created the missing tables. Applied all patched
[2019-10-08 11:11:03,131::INFO::PyFunceble/clean.py:233@almost_everything](PID12731): Cleaned the data related to '/home/mitchellkrog/PyFuncebleTests/Phishing.Domains/input/ALL-feeds.lst' from the pyfunceble_tested table.
[2019-10-08 11:11:03,205::INFO::PyFunceble/auto_continue.py:474@get_already_tested](PID12731): Getting the list of already tested (DATASET WONT BE LOGGED)
[2019-10-08 11:11:03,223::INFO::PyFunceble/inactive_db.py:564@get_already_tested](PID12731): Getting the list of already tested (DATASET WONT BE LOGGED)
[2019-10-08 11:11:03,885::INFO::PyFunceble/dns_lookup.py:100@__init__](PID12731): DNS Server explicitly given, using the given one.
[2019-10-08 11:11:03,887::INFO::PyFunceble/dns_lookup.py:186@a_record](PID12731): Getting A record of '027sn.com'
[2019-10-08 11:16:22,550::INFO::PyFunceble/__init__.py:1535@_command_line](PID16310): ARGS:
Namespace(adblock=False, aggressive=False, all=True, auto_continue=False, autosave_minutes=None, clean=False, clean_all=False, cmd=None, cmd_before_end=None, commit_autosave_message=None, commit_results_message=None, complements=False, database=False, database_type='mariadb', days_between_db_retest=None, debug=True, directory_structure=False, dns=['158.69.2.23'], domain=None, execution=True, file='/home/mitchellkrog/PyFuncebleTests/Phishing.Domains/input/ALL-feeds.lst', filter=None, hierarchical=False, host=False, http=False, iana=False, idna=True, ip=None, json=False, less=False, link=None, local=False, mining=False, multiprocess=False, no_files=False, no_logs=False, no_special=False, no_unified=False, no_whois=False, percentage=False, plain=True, processes=None, production=False, public_suffix=False, quiet=False, share_logs=False, simple=False, split=False, syntax=False, timeout=2, travis=False, travis_branch='master', url=None, url_file=None, user_agent=None, verify_ssl_certificate=False, whois_database=False)
[2019-10-08 11:16:22,947::INFO::PyFunceble/mysql.py:317@create_tables_and_apply_patches](PID16310): Created the missing tables. Applied all patched
[2019-10-08 11:16:22,948::INFO::PyFunceble/auto_save.py:97@__init__](PID16310): Authorized: False
[2019-10-08 11:16:22,949::INFO::PyFunceble/inactive_db.py:521@get_to_retest](PID16310): Getting the list of subjects to retest (DATASET WONT BE LOGGED)
[2019-10-08 11:16:23,859::INFO::PyFunceble/auto_continue.py:108@__init__](PID16310): Process authorized.
[2019-10-08 11:16:23,859::INFO::PyFunceble/auto_continue.py:130@__init__](PID16310): Process authorized, is the parent process and the file to test not indexed. Cleaning directory structure.
[2019-10-08 11:16:23,871::INFO::PyFunceble/mysql.py:317@create_tables_and_apply_patches](PID16310): Created the missing tables. Applied all patched
[2019-10-08 11:16:23,874::INFO::PyFunceble/clean.py:233@almost_everything](PID16310): Cleaned the data related to '/home/mitchellkrog/PyFuncebleTests/Phishing.Domains/input/ALL-feeds.lst' from the pyfunceble_tested table.
[2019-10-08 11:16:23,946::INFO::PyFunceble/auto_continue.py:474@get_already_tested](PID16310): Getting the list of already tested (DATASET WONT BE LOGGED)
[2019-10-08 11:16:23,963::INFO::PyFunceble/inactive_db.py:564@get_already_tested](PID16310): Getting the list of already tested (DATASET WONT BE LOGGED)
[2019-10-08 11:16:24,670::INFO::PyFunceble/dns_lookup.py:100@__init__](PID16310): DNS Server explicitly given, using the given one.
[2019-10-08 11:16:24,672::INFO::PyFunceble/dns_lookup.py:186@a_record](PID16310): Getting A record of '027sn.com'
